export const AUTH_DATA_USER = 'AUTH_DATA_USER'
export const AUTH_LOGOUT = 'AUTH_LOGOUT'
export const DATA_USER = 'DATA_USER'
export const DATA_ZAPIS = 'DATA_ZAPIS'
export const ADD_ZAPIS = 'ADD_ZAPIS'
export const LOADING = 'LOADING'
export const DATA_COMMENTS = 'DATA_COMMENTS'
export const ADD_COMMENT = 'ADD_COMMENT'